-- Generated by nwg-displays on 2026-08-07 at 07:29:12. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@60.0",
    position = "6804x2145",
    scale = 1.5
})
hl.monitor({
    output = "DP-12",
    mode = "1920x1080@60.0",
    position = "2964x2265",
    scale = 1.0
})
hl.monitor({
    output = "DP-13",
    mode = "1920x1080@60.0",
    position = "4884x2265",
    scale = 1.0
})
