#!/usr/bin/env bash
# Detect this machine's GPU topology and generate the two machine-specific
# pieces the Hyprland config needs, so the same repo works on any box:
#
#   ~/.config/hypr/gpu.conf              (sourced by hyprland.conf; NOT stowed)
#   /etc/udev/rules.d/99-hypr-gpu.rules  (hybrid setups only; needs sudo)
#
# Idempotent; re-run after any GPU/hardware change. See docs/hardware.md.
set -euo pipefail

GPU_CONF="$HOME/.config/hypr/gpu.conf"
RULE=/etc/udev/rules.d/99-hypr-gpu.rules

# lspci lines for display controllers, e.g. "65:00.0 VGA ... [1002:1900]"
mapfile -t gpus < <(lspci -Dnn | grep -Ei 'VGA compatible controller|3D controller|Display controller')

# Match on PCI vendor IDs only — vendor NAMES are trap-laden ("ATI" is inside
# "Corporation", so every NVIDIA line matches an AMD name grep).
addr_of() { grep -Fm1 "[$1:" <<<"$(printf '%s\n' "${gpus[@]}")" | awk '{print $1}'; }
AMD=$(addr_of 1002 || true)
NV=$(addr_of 10de || true)
INTEL=$(addr_of 8086 || true)
IGPU="${AMD:-$INTEL}"

mkdir -p "$(dirname "$GPU_CONF")"

write_rule() { # write_rule <igpu-addr> <nv-addr>
    echo "==> installing $RULE ($1 -> igpu-card, $2 -> nv-card)"
    sudo tee "$RULE" >/dev/null <<EOF
# Generated by tools/gen-gpu-conf.sh — stable colon-free DRM symlinks for
# Hyprland AQ_DRM_DEVICES (Aquamarine splits on ":", PCI by-path names contain
# them). Re-run the script if GPU PCI addresses change.
KERNEL=="card*", KERNELS=="$1", SYMLINK+="dri/igpu-card"
KERNEL=="card*", KERNELS=="$2", SYMLINK+="dri/nv-card"
EOF
    sudo udevadm control --reload-rules
    sudo udevadm trigger --subsystem-match=drm --action=add
}

if [[ -n "$IGPU" && -n "$NV" ]]; then
    # Hybrid iGPU + NVIDIA: iGPU first = primary renderer + allocator (NVIDIA
    # first crashes Aquamarine's GBM allocator on these setups); NVIDIA second
    # scans out whatever panels are wired to it. VAAPI must match the PRIMARY
    # RENDERER (apps render on the iGPU), not the discrete card — the wrong
    # driver silently kills hardware video decode.
    [[ -n "$AMD" ]] && VAAPI=radeonsi || VAAPI=iHD
    write_rule "$IGPU" "$NV"
    cat > "$GPU_CONF" <<EOF
# Generated by tools/gen-gpu-conf.sh — hybrid iGPU ($IGPU) + NVIDIA ($NV).
# Do not edit by hand; re-run the script instead. Docs: docs/hardware.md.
env = AQ_DRM_DEVICES,/dev/dri/igpu-card:/dev/dri/nv-card
env = LIBVA_DRIVER_NAME,$VAAPI
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
# GBM_BACKEND=nvidia-drm intentionally NOT set: breaks the iGPU side on hybrids.
EOF
elif [[ -n "$NV" ]]; then
    echo "==> NVIDIA-only box: no udev rule/AQ_DRM_DEVICES needed"
    sudo rm -f "$RULE" 2>/dev/null || true
    cat > "$GPU_CONF" <<EOF
# Generated by tools/gen-gpu-conf.sh — single NVIDIA GPU ($NV).
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = GBM_BACKEND,nvidia-drm
EOF
else
    echo "==> AMD/Intel-only box: mesa defaults are fine"
    sudo rm -f "$RULE" 2>/dev/null || true
    [[ -n "$AMD" ]] && VAAPI=radeonsi || VAAPI=iHD
    cat > "$GPU_CONF" <<EOF
# Generated by tools/gen-gpu-conf.sh — no NVIDIA GPU detected.
env = LIBVA_DRIVER_NAME,$VAAPI
EOF
fi

echo "==> wrote $GPU_CONF:"
sed 's/^/    /' "$GPU_CONF"
echo "Restart Hyprland for env changes to take effect."
